# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      # Copy the appropriate conf.py based on project name
      - |
        if [ "$READTHEDOCS_PROJECT" = "brainpy-version2" ]; then
          mkdir -p docs_build
          cp -r docs_version2/* docs_build/
        else
          mkdir -p docs_build
          cp -r docs/* docs_build/
        fi

# Build documentation using the copied conf.py
sphinx:
  configuration: docs_build/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: requirements-doc.txt

