
from brainpy._src.math.compat_pytorch import (
  Tensor as Tensor,

  flatten as flatten,
  cat as cat,
  unsqueeze as unsqueeze,
  abs as abs,
  absolute as absolute,
  acos as acos,
  arccos as arccos,
  acosh as acosh,
  arccosh as arccosh,
  add as add,
  addcdiv as addcdiv,
  addcmul as addcmul,
  angle as angle,
  asin as asin,
  arcsin as arcsin,
  asinh as asinh,
  arcsin as arcsin,
  atan as atan,
  arctan as arctan,
  atan2 as atan2,
  atanh as atanh,
)
